---
version: '3'
services:
  postgres:
    image: postgres:13.0
    shm_size: 4g
    restart: always
    network_mode: "host"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DaVinci
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - "/volume1/YourPGSQLDestinationFolder:/var/lib/postgresql/data" ; path to postgresql destination  
pgbackups:
    image: prodrigestivill/postgres-backup-local:13
    restart: always
    volumes:
      - "/volume1/YourBackupDestinationFolder:/backups" ; path to resolve backup folder
    network_mode: "host"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DaVinci
      - POSTGRES_EXTRA_OPTS=--blobs --format=custom --quote-all-identifiers
      - BACKUP_SUFFIX=.backup
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
      - TZ=Asia/Kuala_Lumpur
volumes:
  resolve-db:
